"""Initial schema

Revision ID: 595cb54b9c1b
Revises: None
Create Date: 2026-09-01 14:22:47.599573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595cb54b9c1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_name', sa.String(), nullable=False),
    sa.Column('total_guards', sa.Integer(), nullable=False),
    sa.Column('total_gross_pay', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('total_net_pay', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('closed_by', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_payroll_id'), 'archive_payroll', ['id'], unique=False)
    op.create_index(op.f('ix_archive_payroll_month'), 'archive_payroll', ['month'], unique=False)
    op.create_index(op.f('ix_archive_payroll_payroll_period_id'), 'archive_payroll', ['payroll_period_id'], unique=True)
    op.create_index(op.f('ix_archive_payroll_year'), 'archive_payroll', ['year'], unique=False)
    op.create_table('archive_payroll_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_payroll_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('guard_name', sa.String(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=False),
    sa.Column('regular_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('basic_pay', sa.Float(), nullable=False),
    sa.Column('overtime_pay', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=False),
    sa.Column('gross_pay', sa.Float(), nullable=False),
    sa.Column('nssf_deduction', sa.Float(), nullable=False),
    sa.Column('shif_deduction', sa.Float(), nullable=False),
    sa.Column('housing_levy_deduction', sa.Float(), nullable=False),
    sa.Column('paye_deduction', sa.Float(), nullable=False),
    sa.Column('other_deductions', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('bank_account_or_mpesa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_payroll_items_archive_payroll_id'), 'archive_payroll_items', ['archive_payroll_id'], unique=False)
    op.create_index(op.f('ix_archive_payroll_items_guard_id'), 'archive_payroll_items', ['guard_id'], unique=False)
    op.create_index(op.f('ix_archive_payroll_items_id'), 'archive_payroll_items', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('payroll_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_periods_id'), 'payroll_periods', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shift_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('night_allowance', sa.Float(), nullable=False),
    sa.Column('transport_allowance', sa.Float(), nullable=False),
    sa.Column('housing_allowance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_site_name'), 'sites', ['site_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('guards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('mpesa_number', sa.String(), nullable=True),
    sa.Column('nssf_number', sa.String(), nullable=True),
    sa.Column('shif_number', sa.String(), nullable=True),
    sa.Column('kra_pin', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deactivation_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id')
    )
    op.create_index(op.f('ix_guards_employee_number'), 'guards', ['employee_number'], unique=True)
    op.create_index(op.f('ix_guards_full_name'), 'guards', ['full_name'], unique=False)
    op.create_index(op.f('ix_guards_id'), 'guards', ['id'], unique=False)
    op.create_index(op.f('ix_guards_phone'), 'guards', ['phone'], unique=False)
    op.create_table('payment_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_schedules_id'), 'payment_schedules', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('actual_clock_in', sa.DateTime(), nullable=True),
    sa.Column('actual_clock_out', sa.DateTime(), nullable=True),
    sa.Column('regular_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('flagged_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_guard_id'), 'attendance', ['guard_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_shift_date'), 'attendance', ['shift_date'], unique=False)
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('benefit_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefits_guard_id'), 'benefits', ['guard_id'], unique=False)
    op.create_index(op.f('ix_benefits_id'), 'benefits', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_guard_id'), 'documents', ['guard_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_guard_id'), 'incidents', ['guard_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_reference_number'), 'incidents', ['reference_number'], unique=True)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_guard_id'), 'leave_requests', ['guard_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_table('payment_schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_schedule_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('mpesa_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['payment_schedule_id'], ['payment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_schedule_items_id'), 'payment_schedule_items', ['id'], unique=False)
    op.create_table('payroll_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_errors_id'), 'payroll_errors', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_errors_payroll_period_id'), 'payroll_errors', ['payroll_period_id'], unique=False)
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=False),
    sa.Column('regular_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('basic_pay', sa.Float(), nullable=False),
    sa.Column('overtime_pay', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=False),
    sa.Column('gross_pay', sa.Float(), nullable=False),
    sa.Column('nssf_deduction', sa.Float(), nullable=False),
    sa.Column('shif_deduction', sa.Float(), nullable=False),
    sa.Column('housing_levy_deduction', sa.Float(), nullable=False),
    sa.Column('paye_deduction', sa.Float(), nullable=False),
    sa.Column('other_deductions', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_records_guard_id'), 'payroll_records', ['guard_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_id'), 'payroll_records', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_records_payroll_period_id'), 'payroll_records', ['payroll_period_id'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('certificate_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_guard_id'), 'training_records', ['guard_id'], unique=False)
    op.create_index(op.f('ix_training_records_id'), 'training_records', ['id'], unique=False)
    op.create_table('payroll_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_record_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_deductions_id'), 'payroll_deductions', ['id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_record_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('payslip_number', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payslip_number')
    )
    op.create_index(op.f('ix_payslips_guard_id'), 'payslips', ['guard_id'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_guard_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payroll_deductions_id'), table_name='payroll_deductions')
    op.drop_table('payroll_deductions')
    op.drop_index(op.f('ix_training_records_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_guard_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_payroll_records_payroll_period_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_guard_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index(op.f('ix_payroll_errors_payroll_period_id'), table_name='payroll_errors')
    op.drop_index(op.f('ix_payroll_errors_id'), table_name='payroll_errors')
    op.drop_table('payroll_errors')
    op.drop_index(op.f('ix_payment_schedule_items_id'), table_name='payment_schedule_items')
    op.drop_table('payment_schedule_items')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_guard_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_incidents_reference_number'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_guard_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_guard_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_benefits_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_guard_id'), table_name='benefits')
    op.drop_table('benefits')
    op.drop_index(op.f('ix_attendance_shift_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_guard_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_payment_schedules_id'), table_name='payment_schedules')
    op.drop_table('payment_schedules')
    op.drop_index(op.f('ix_guards_phone'), table_name='guards')
    op.drop_index(op.f('ix_guards_id'), table_name='guards')
    op.drop_index(op.f('ix_guards_full_name'), table_name='guards')
    op.drop_index(op.f('ix_guards_employee_number'), table_name='guards')
    op.drop_table('guards')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_site_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_archive_payroll_items_id'), table_name='archive_payroll_items')
    op.drop_index(op.f('ix_archive_payroll_items_guard_id'), table_name='archive_payroll_items')
    op.drop_index(op.f('ix_archive_payroll_items_archive_payroll_id'), table_name='archive_payroll_items')
    op.drop_table('archive_payroll_items')
    op.drop_index(op.f('ix_archive_payroll_year'), table_name='archive_payroll')
    op.drop_index(op.f('ix_archive_payroll_payroll_period_id'), table_name='archive_payroll')
    op.drop_index(op.f('ix_archive_payroll_month'), table_name='archive_payroll')
    op.drop_index(op.f('ix_archive_payroll_id'), table_name='archive_payroll')
    op.drop_table('archive_payroll')
    # ### end Alembic commands ###
