// CorpSec HR Payroll — RFC-4180 Compliant CSV & Excel Export Utility

export interface CsvColumn<T = any> {
  header: string;
  key: keyof T | string;
  formatter?: (val: any, row: T) => string | number;
}

export interface CsvExportOptions<T = any> {
  title?: string;
  periodName?: string;
  generatedBy?: string;
  columns: CsvColumn<T>[];
  data: T[];
  totalsKeys?: string[];
}

export class CsvExporter {
  public static generate<T = any>(options: CsvExportOptions<T>): string {
    const lines: string[] = [];

    // Header metadata
    lines.push(`"CORPSEC HR & PAYROLL MANAGEMENT SYSTEM"`);
    if (options.title) lines.push(`"${options.title.replace(/"/g, '""')}"`);
    if (options.periodName) lines.push(`"Payroll Period: ${options.periodName.replace(/"/g, '""')}"`);
    lines.push(`"Generated At: ${new Date().toISOString()}"`);
    if (options.generatedBy) lines.push(`"Generated By: ${options.generatedBy.replace(/"/g, '""')}"`);
    lines.push(''); // Blank separator

    // Column Headers
    const headerRow = options.columns.map((c) => `"${c.header.replace(/"/g, '""')}"`).join(',');
    lines.push(headerRow);

    // Totals tracking accumulator
    const totals: Record<string, number> = {};
    if (options.totalsKeys) {
      for (const k of options.totalsKeys) {
        totals[k] = 0;
      }
    }

    // Data Rows
    for (const row of options.data) {
      const values: string[] = [];

      for (const col of options.columns) {
        let val = (row as any)[col.key];

        if (col.formatter) {
          val = col.formatter(val, row);
        }

        // Track numeric totals
        if (options.totalsKeys && options.totalsKeys.includes(col.key as string)) {
          const num = Number((row as any)[col.key]);
          if (!isNaN(num)) {
            totals[col.key as string] = (totals[col.key as string] || 0) + num;
          }
        }

        if (val === null || val === undefined) {
          values.push('""');
        } else if (typeof val === 'number') {
          values.push(val.toFixed(2));
        } else {
          values.push(`"${String(val).replace(/"/g, '""')}"`);
        }
      }

      lines.push(values.join(','));
    }

    // Totals Row
    if (options.totalsKeys && options.totalsKeys.length > 0) {
      lines.push('');
      const totalValues: string[] = [];
      let isFirstText = true;

      for (const col of options.columns) {
        if (options.totalsKeys.includes(col.key as string)) {
          const sum = totals[col.key as string] || 0;
          totalValues.push(sum.toFixed(2));
        } else if (isFirstText) {
          totalValues.push('"TOTALS"');
          isFirstText = false;
        } else {
          totalValues.push('""');
        }
      }
      lines.push(totalValues.join(','));
    }

    return lines.join('\r\n');
  }
}
